from config import CROPPED_IMAGES, PIPELINE_B_SEG_IMAGES, PIPELINE_A_SEG_IMAGES, PIPELINE_C_SEG_IMAGES, PIPELINE_B_DIM_IMAGES, PIPELINE_B_FULL_DIM_IMAGES, PIPELINE_A_FULL_DIM_IMAGES, PIPELINE_C_FULL_DIM_IMAGES, PIPELINE_A_EVAL_IMAGES, PIPELINE_B_EVAL_IMAGES, PIPELINE_C_EVAL_IMAGES,PIPELINE_A_EVAL_IMAGES_CONF, PIPELINE_B_EVAL_IMAGES_CONF, PIPELINE_C_EVAL_IMAGES_CONF

import os

def create_folders():
    for path in [CROPPED_IMAGES, PIPELINE_B_SEG_IMAGES, PIPELINE_A_SEG_IMAGES, PIPELINE_C_SEG_IMAGES, PIPELINE_B_DIM_IMAGES, PIPELINE_B_FULL_DIM_IMAGES, PIPELINE_A_FULL_DIM_IMAGES, PIPELINE_C_FULL_DIM_IMAGES, PIPELINE_A_EVAL_IMAGES, PIPELINE_B_EVAL_IMAGES, PIPELINE_C_EVAL_IMAGES, PIPELINE_A_EVAL_IMAGES_CONF, PIPELINE_B_EVAL_IMAGES_CONF, PIPELINE_C_EVAL_IMAGES_CONF]:
        if not os.path.exists(path):
            os.makedirs(path)